export default [
  {
    id: '1',
    icon: 'dashboard',
    name: '仪表盘',
    route: '/dashboard',
  },
  {
    id: '2',
    breadcrumbParentId: '1',
    name: '公告管理',
    icon: 'icon-sunny',
    route: '/announcement',
  },
  {
    name: '文章管理',
    breadcrumbParentId: '1',
    icon: 'edit',
    id: '3',
  },
  {
    route: '/article/list',
    icon: 'align-left',
    breadcrumbParentId: '3',
    menuParentId: '3',
    name: '所有文章',
    id: '31',
  },

  {
    route: '/article/category',
    menuParentId: '3',
    breadcrumbParentId: '3',
    icon: 'folder-open',
    name: '分类目录',
    id: '32',
  },
  {
    route: '/article/post',
    menuParentId: '3',
    breadcrumbParentId: '3',
    icon: 'export',
    name: '发布文章',
    id: '33',
  },
  {
    route: '/article/tag',
    icon: 'tags',
    menuParentId: '3',
    breadcrumbParentId: '3',
    name: '文章标签',
    id: '34',
  },
  {
    route: '/article/edit/:id',
    breadcrumbParentId: '3',
    icon: 'edit',
    menuParentId: '-1',
    name: '修改文章',
    id: '35',
  },
  {
    name: '评论管理',
    icon: 'message',
    id: '4',
    breadcrumbParentId: '1',
  },
  {
    route: '/comment/list',
    name: '所有评论',
    icon: 'icon-list',
    menuParentId: '4',
    breadcrumbParentId: '4',
    id: '41',
  },
  {
    route: '/comment/post/0',
    name: '留言评论',
    menuParentId: '4',
    breadcrumbParentId: '4',
    icon: 'icon-list',
    id: '42',
  },
  {
    route: '/comment/post/:post_id',
    name: '文章评论',
    menuParentId: '-1',
    breadcrumbParentId: '4',
    icon: 'icon-list',
    id: '43',
  },
  {
    route: '/comment/detail/:id',
    name: '文章评论',
    menuParentId: '-1',
    breadcrumbParentId: '4',
    icon: 'icon-list',
    id: '44',
  },
  {
    route: '/options',
    name: '全局设置',
    icon: 'setting',
    id: '10',
  },
  // {
  //   route: '/linux',
  //   hideInMenu: true,
  //   name: 'Aliyun管理',
  //   icon: 'icon-logo-tux',
  //   id: '9',
  // },
  {
    name: 'Google Analytics',
    route: 'https://analytics.google.com',
    icon: 'google',
    id: 800,
    target: '_blank',
  },
  {
    name: 'Github',
    route: 'https://github.com/huhuang777',
    icon: 'github',
    id: '900',
    target: '_blank',
  },
]
